#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # this comment is required
# The above line ensures that the script can be run on Cygwin/Linux even with Windows CRNL
#
# gp - run the geoprocessor, defaulting to command mode
#
# See also gpui to run the UI.

# Script to run the Open Water Foundation GeoProcessor application for QGIS
# - This script is for Python3/QGIS3 (QGIS LTR is not used)
# - This script should work on Linux and Cygwin running on Windows 7/10 computer
# - The geoprocessor package must be installed in a normal location, such as
#   QGIS Python site-packages folder.
# - This script should be installed in the QGIS bin folder or other location
#   that is in the PATH or otherwise can be executed.
# - The logic of this script closely matches the gp.bat batch file.

# Supporting functions

# Determine the operating system that is running the script
# - set operatingSystem to "linux", "cygwin", or "mingw" (Git Bash)
checkOperatingSystem()
{
	if [ ! -z "${operatingSystem}" ]; then
		# Have already checked operating system so return
		return
	fi
	operatingSystem="unknown"
	os=`uname | tr [a-z] [A-Z]`
	case "${os}" in
		CYGWIN*)
			# Cygwin
			operatingSystem="cygwin"
			;;
		LINUX*)
			# Linux variants
			operatingSystem="linux"
			echo "Linux version of GeoProcessor with QGIS is not yet supported."
			exit 1
			;;
		MINGW*)
			# Git Bash
			operatingSystem="mingw"
			;;
	esac
	echo "operatingSystem=${operatingSystem}"
}

# Set the Python environment to find the correct QGIS run-time libraries for Cygwin
# - The GEOPROCESSOR_ENV_SETUP environment variable is set to YES
#   to indicate that setup has been done.
# - This causes setup to occur only once if rerunning this batch file.
# - Actually, this just sets local environment variables for some since
#   unlike windows the shell can more easily be initialized each time the script runs
configCygwinEnv () {
	if [ "${GEOPROCESSOR_ENV_SETUP}" == "YES" ]; then
		# Environment is already configured
		return
	fi
	# If here do the setup one time first time batch file is run in a command shell
	# Start defining QGIS GeoProcessor environment...

	# Where QGIS is installed
	
	if [ "${operatingSystem}" = "cygwin" ]; then
		QGIS_INSTALL_HOME=/cygdrive/C/OSGeo4W64
	elif [ "${operatingSystem}" = "linux" ]; then
		# TODO add later
		echo "linux is not yet supported"
	elif [ "${operatingSystem}" = "mingw" ]; then
		QGIS_INSTALL_HOME=/C/OSGeo4W64
	fi

	if [ ! -d "$QGIS_INSTALL_HOME" ]; then
		# Print error message and exit
		noQgis
	fi

	# Set the QGIS environment by calling the setup batch files that are distributed with QGIS
	# - the following will reset the PATH and then add QGIS folders to path
	# - therefore other programs that were found before may not be found
	# - this effectively isolates QGIS from the system
	# - OK to call from Cygwin or Git Bash since they somehow use the Windows PATH?
	#export OSGEO4W_ROOT="$QGIS_INSTALL_HOME"
	# Apparently need to use the old-style short DOS filenames
	export OSGEO4W_ROOT="/cygdrive/c/OSGEO4~1"
	echo "Setting up QGIS by running: $OSGEO4W_ROOT/bin/o4w_env.bat"
	# Running a bat file does not expose the variables in this shell so set the variables here
	# - OSGEO4W_ROOT is set above
	# - Changes to path may not be needed so don't do yet.
	# - Also calls $OSGEO4W_ROOT/etc/ini/*.bat to set variables for libraries/plugins? - may need to set
	#$OSGEO4W_ROOT/bin/o4w_env.bat
	echo "... done setting up QGIS by running: $OSGEO4W_ROOT/bin/o4w_env.bat"

	# The following sets a number of QT environment variables (QT is used in the UI)
	echo "Setting up QT5 by running: $OSGEO4W_ROOT/bin/qt5_env.bat"
	# Similar to the above, environment variables do not propagate up so set here
	#$OSGEO4W_ROOT/bin/qt5_env.bat
	export PATH="$OSGEO4W_ROOT/apps/qt5/bin:$PATH"
	export QT_PLUGIN_PATH=$OSGEO4W_ROOT/apps/Qt5/plugins

	export O4W_QT_PREFIX=$OSGEO4W_ROOT/apps/Qt5
	export O4W_QT_BINARIES=$OSGEO4W_ROOT/apps/Qt5/bin
	export O4W_QT_PLUGINS=$OSGEO4W_ROOT/apps/Qt5/plugins
	export O4W_QT_LIBRARIES=$OSGEO4W_ROOT/apps/Qt5/lib
	export O4W_QT_TRANSLATIONS=$OSGEO4W_ROOT/apps/Qt5/translations
	export O4W_QT_HEADERS=$OSGEO4W_ROOT/apps/Qt5/include
	echo "...done setting up QT5 by running: $OSGEO4W_ROOT/bin/qt5_env.bat"
	# The following sets:
	# - PYTHONHOME to Python shipped with QGIS
	# - Clears PYTHONPATH
	# - PATH to include Python shipped with QGIS and Python scripts folder
	echo "Setting up QT5 by running: $OSGEO4W_ROOT/bin/py3_env.bat"
	# Similar to the above, environment variables do not propagate up so set here
	#$OSGEO4W_ROOT/bin/py3_env.bat
	export PYTHONPATH=""
	export PYTHONHOME="$OSGEO4W_ROOT/apps/Python36"
	export PATH="$OSGEO4W_ROOT/apps/Python36:$OSGEO4W_ROOT/apps/Python36/Scripts:$PATH"
	echo "...done setting up QT5 by running: $OSGEO4W_ROOT/bin/py3_env.bat"

	# Name of QGIS version to run (**for running GeoProcessor don't run QGIS but need to use correct QGIS components**).
	# Run the latest release of the OSGeo4W QGIS by setting value to `qgis`.
	# Running the long-term release of the OSGeo4W QGIS by setting value to `qgis-ltr` is not supported.
	QGISNAME=qgis
	echo "QGISNAME is $QGISNAME"

	# Add QGIS to the PATH environment variable so that all QGIS, GDAL, OGR, etc. programs are found.
	echo OSGEO4W_ROOT=$OSGEO4W_ROOT
	export PATH="$OSGEO4W_ROOT/bin:$PATH"
	export PATH="$PATH:$OSGEO4W_ROOT/apps/$QGISNAME/bin"

	QGIS_PREFIX_PATH="$OSGEO4W_ROOT/apps/$QGISNAME"
	export GDAL_FILENAME_IS_UTF8=YES
	# --
	# Set VSI cache to be used as buffer, see https://issues.qgis.org/issues/6448
	export VSI_CACHE=TRUE
	export VSI_CACHE_SIZE=1000000
	# --

	export QT_PLUGIN_PATH="$OSGEO4W_ROOT/apps/$QGISNAME/qtplugins:$OSGEO4W_ROOT/apps/qt5/plugins"

	# Add pyQGIS libraries to the PYTHONPATH so that they are found by Python
	export PYTHONPATH=$OSGEO4W_ROOT/apps/$QGISNAME/python:$PYTHONPATH
	# See https://anitagraser.com/2018/01/28/porting-processing-scripts-to-qgis3/
	export PYTHONPATH=$OSGEO4W_ROOT/apps/$QGISNAME/python/plugins:$PYTHONPATH
	export PYTHONPATH=$OSGEO4W_ROOT/apps/Python36/lib/site-packages:$PYTHONPATH

	# Indicate that the setup has been completed
	# - this will ensure that the script when run again does not repeat setup
	#   and keep appending to environment variables
	export GEOPROCESSOR_ENV_SETUP=YES
	echo "...done defining QGIS GeoProcessor environment for Cygwin"
}

# Print a message and exit if QGIS was not found
noQgis () {
	# QGIS install folder was not found
	echo "QGIS standard installation folder was not found:  ${QGIS_INSTALL_HOME}"
	exit 1
}

# Run Python for the GeoProcessor module
runProcessor() {
	# Echo environment variables for troubleshooting
	echo ""
	echo "Using Python3/QGIS3 for GeoProcessor"
	echo "OSGEO4W_ROOT=$OSGEO4W_ROOT"
	echo "PATH=$PATH"
	echo "PYTHONHOME=$PYTHONHOME"
	echo "PYTHONPATH=$PYTHONPATH"
	echo "QGIS_PREFIX_PATH=$QGIS_PREFIX_PATH"
	echo "QT_PLUGIN_PATH=$QT_PLUGIN_PATH"
	echo ""

	# Run QGIS Python with the geoprocessor module found using PYTHONPATH set above.
	# - Must use Python 3.6 compatible with QGIS
	# - Pass command line arguments that were passed to this bat file.
	# "%PYTHONHOME%\python" %*
	# Use -v to see verbose list of modules that are loaded.
	echo "Running: $PYTHONHOME/python -m geoprocessor.app.gp $@"
	$PYTHONHOME/python -m geoprocessor.app.gp $@

	# Run the following to use the environment but be able to do imports, etc. to find modules
	# "$PYTHONHOME\python -v

	# Exit with the error level of the Python command
	exit $?
}

# Main entry point into the script

# Check the operating system
checkOperatingSystem
# Configure the environment (if not already configured)
if [ "${operatingSystem}" = "cygwin" ]; then
	configCygwinEnv
elif [ "${os}" = "mingw" ]; then
	echo "Operating system ${os} is not supported."
else
	echo "Unknown operating system ${os}"
	exit 1
fi

# Run the processor, will exit with status
runProcessor
