#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # this comment is required
# The above line ensures that the script can be run on Cygwin/Linux even with Windows CRNL
#
# gptestui
#_________________________________________________________________NoticeStart_
# GeoProcessor
# Copyright (C) 2017-2020 Open Water Foundation
# 
# GeoProcessor is free software:  you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     GeoProcessor is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with GeoProcessor.  If not, see <https://www.gnu.org/licenses/>.
#_________________________________________________________________NoticeEnd___
#
# Simple script to run the Open Water Foundation GeoProcessor application user interface, for test framework
# - if it does not work, make sure that gptest works

# Supporting functions, alphabetized

# Determine the operating system that is running the script
# - sets the variable operatingSystem to cygwin, linux, or mingw (Git Bash)
checkOperatingSystem()
{
	if [ ! -z "${operatingSystem}" ]; then
		# Have already checked operating system so return
		return
	fi
	operatingSystem="unknown"
	os=`uname | tr [a-z] [A-Z]`
	case "${os}" in
		CYGWIN*)
			operatingSystem="cygwin"
			;;
		LINUX*)
			operatingSystem="linux"
			;;
		MINGW*)
			operatingSystem="mingw"
			;;
	esac
	# echo "Detected operatingSystem=$operatingSystem"
}

# Function to set the title of the terminal so can better identify what it is being used for
# - see:  https://askubuntu.com/questions/22413/how-to-change-gnome-terminal-title
# - this is done
setTerminalTitle () {
	checkOperatingSystem
	if [ "${operatingSystem}" = cygwin ]; then
		# A simple title is OK
		# - the environment gets set in a subshell so does not continue after closing this shell
		title="GeoProcessor (gptest run with gptestui)"
	elif [ "${operatingSystem}" = linux ]; then
		# A simple title is OK
		# - the environment gets set in a subshell so does not continue after closing this shell
		title="GeoProcessor (gptest run with gptestui)"
	elif [ "${operatingSystem}" = linux ]; then
		# MinGW has not been tested
		title="GeoProcessor (gptest run with gptestui) running on MinGW has not been tested"
	else
		# Unknown operating system, don't know if environment will work
		title="GeoProcessor (gptest run with gptestui) unknown operating system - may not work"
	fi
	# Set the title
	echo -ne "\033]0;${title}\007"
}

# Main entry point into the script

# Get the location where this script is located since it may have been run from any folder
scriptFolder=`cd $(dirname "$0") && pwd`

# Set the terminal title to help users know this is a window where GeoProcessor is being run
# - the title will persist after the program is run, but that is generally OK
# - this is particularly useful for software developers that have multiple windows opened and can get confused
setTerminalTitle

# Run the main script with full path since it may not be in the PATH
${scriptFolder}/gptest --ui $@

# Exit with the status of the called script
exit $?
