#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # this comment is required
# The above line ensures that the script can be run on Cygwin/Linux even with Windows CRNL
#
# gptestui

# Simple script to run the Open Water Foundation GeoProcessor application user interface, for test framework
# - if it does not work, make sure that gptest works

# Get the location where this script is located since it may have been run from any folder
scriptFolder=`cd $(dirname "$0") && pwd`

# Set the DISPLAY variable needed for X windows
if [ -z "$DISPLAY" ]; then
	echo "Setting DISPLAY=:0.0"
	export DISPLAY=0.0
fi

# Run the main script with full path since it may not be in the PATH
${scriptFolder}/gptest --ui $@

# Exit with the status of the called script
exit $?
