#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # this comment is required
# The above line ensures that the script can be run on Cygwin/Linux even with Windows CRNL
#
# gpui

# Simple script to run the Open Water Foundation GeoProcessor application user interface.
# - if it does not work, make sure that gp works

# Get the location where this script is located since it may have been run from any folder
scriptFolder=`cd $(dirname "$0") && pwd`

# Run the GeoProcessor using the main script
${scriptFolder}/gp --ui $@

# Exit with the status of the called script
exit $?
