# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / OWF GeoProcessor (Dev)
pages:
- Home: index.md
- Introduction: introduction.md
- New Developer: dev-new.md
- Software Design: software-design.md
- Development Tasks: dev-tasks.md
- Development Environment: dev-env.md
- Resources: resources.md
- Troubleshooting: troubleshooting.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't specify the repository because doing show shows irritating edit
# icons on every page - instead, edit the documentation in the developer environment.
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python
site_description:  Open Water Foundation Learn GeoProcessor (for Developers)
site_author:  Open Water Foundation
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
