# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'GeoProcessor (Developer)'
pages:
- Home: 'index.md'
- Introduction: 'introduction/introduction.md'
- New Developer: 'dev-new/dev-new.md'
- Software Design: 'software-design/software-design.md'
- UI Design: 'ui-design/ui-design.md'
- UI Design (Old): 'ui-design-old/ui-design-old.md'
- Development Tasks:
  - Overview: dev-tasks/overview.md
  - Version Control: dev-tasks/version-control.md
  - Editing Code: dev-tasks/editing.md
  - Documenting: dev-tasks/documenting.md
  - Running: dev-tasks/running.md
  - Testing: dev-tasks/testing.md
  - Creating Installer: dev-tasks/creating-installer.md
- Development Environment:
  - Overview: 'dev-env/overview.md'
  - Development Folders: 'dev-env/folders.md'
  - Python: 'dev-env/python.md'
  - QGIS: 'dev-env/qgis.md'
  - PyCharm: 'dev-env/pycharm.md'
  - MkDocs: 'dev-env/mkdocs.md'
  - Git: 'dev-env/git.md'
  - Cygwin: 'dev-env/cygwin.md'
  - Running the GeoProcessor: 'dev-env/running.md'
- Troubleshooting: 'troubleshooting/troubleshooting.md'
- Resources:
  - Resources: 'resources/resources.md'
  - 'QGIS Version Install Experiments': 'resources/qgis-version-install-experiments.md'
  - 'Notes on Migration from QGIS2 to QGIS3': 'resources/migrate-qgis2-qgis3.md'
  - 'Notes on Virtual Environment': 'resources/virtualenv-notes.md'
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't specify the repository because doing show shows irritating edit
# icons on every page - instead, edit the documentation in the developer environment.
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python
site_description:  'Open Water Foundation Learn GeoProcessor (for Developers)'
site_author:  'Open Water Foundation'
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
